FROM python:3.12-alpine

WORKDIR /app
COPY . .

RUN apk add --no-cache --virtual .build-deps \
        gcc musl-dev libffi-dev openssl-dev cargo && \
    pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt && \
    apk del .build-deps

EXPOSE 8000
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]

